openapi: 3.0.4
info:
  title: Microsoft Graph Mail API
  description: "Reduced Microsoft Graph v1.0 OpenAPI spec covering Outlook mail operations:\
    \ messages, mail folders, attachments, and related actions. This includes operations\
    \ for sending, reading, organizing, and managing email messages and mail folders\
    \ for the signed-in user."
  version: v1.0
servers:
- url: https://graph.microsoft.com/v1.0
security:
- azureOAuth2:
  - Mail.Read
  - Mail.ReadWrite
  - Mail.Send
tags:
- name: me.message
  description: Operations on messages in the signed-in user's mailbox
- name: me.mailFolder
  description: Operations on mail folders in the signed-in user's mailbox
- name: me.user.Actions
  description: User-level actions such as sending mail
paths:
  /me/messages:
    description: Provides operations to manage the messages property of the microsoft.graph.user
      entity.
    get:
      tags:
      - me.message
      summary: List messages
      description: "Get the messages in the signed-in user's mailbox (including the\
        \ Sent Items and Deleted Items folders). By default, this operation does not\
        \ return hidden messages. Use the includeHiddenMessages query parameter to\
        \ include them in the response."
      operationId: listMessages
    post:
      tags:
      - me.message
      summary: Create message (draft)
      description: "Create a draft of a new message in either JSON or MIME format.\
        \ When using JSON format, you can include an attachment in the same createMessage\
        \ call. Use this to save a draft to the Drafts folder, then send it later."
      operationId: createDraftMessage
  /me/messages/{messageId}:
    description: Provides operations to manage the messages property of the microsoft.graph.user
      entity.
    get:
      tags:
      - me.message
      summary: Get message
      description: "Get the properties and relationships of a message object. You\
        \ can use the $select parameter to get specific properties, including those\
        \ that aren't returned by default."
      operationId: getMessage
    delete:
      tags:
      - me.message
      summary: Delete message
      description: "Delete a message in the specified user's mailbox, or delete a\
        \ relationship of the message."
      operationId: deleteMessage
    patch:
      tags:
      - me.message
      summary: Update message
      description: Update the properties of a message object. Only the properties
        listed in the request body will be updated.
      operationId: updateMessage
  /me/messages/{messageId}/send:
    description: Provides operations to call the send method.
    post:
      tags:
      - me.message
      summary: Send draft message
      description: "Send an existing draft message. The draft message can be a new\
        \ message draft, reply draft, reply-all draft, or a forward draft. This method\
        \ saves the message in the Sent Items folder. Alternatively, send a new message\
        \ in a single operation. Note: This operation has no request body. Content-Length\
        \ is set to 0 internally."
      operationId: sendDraftMessage
  /me/messages/{messageId}/copy:
    description: Provides operations to call the copy method.
    post:
      tags:
      - me.message
      summary: Copy message
      description: Copy a message to a folder within the user's mailbox.
      operationId: copyMessage
  /me/messages/{messageId}/forward:
    description: Provides operations to call the forward method.
    post:
      tags:
      - me.message
      summary: Forward message
      description: "Forward a message using either JSON or MIME format. When using\
        \ JSON format, you can specify either a comment or the body property of the\
        \ message parameter. This method saves the message in the Sent Items folder."
      operationId: forwardMessage
  /me/messages/{messageId}/attachments:
    description: Provides operations to manage the attachments property of the microsoft.graph.message
      entity.
    get:
      tags:
      - me.message
      summary: List attachments
      description: Retrieve a list of attachment objects attached to a message.
      operationId: listAttachments
    post:
      tags:
      - me.message
      summary: Add file attachment
      description: "Use this API to add a file attachment to a message. An attachment\
        \ can be one of the following types: fileAttachment, itemAttachment, or referenceAttachment.\
        \ All these types of attachment resources are derived from the attachment\
        \ resource. For file attachments smaller than 3 MB, use this endpoint. For\
        \ larger files, use the createUploadSession endpoint."
      operationId: addAttachment
  /me/messages/{messageId}/attachments/{attachmentId}:
    description: Provides operations to manage the attachments property of the microsoft.graph.message
      entity.
    get:
      tags:
      - me.message
      summary: Get attachment
      description: "Read the properties, relationships, or raw contents of an attachment\
        \ attached to a user message. An attachment can be one of the following types:\
        \ fileAttachment, itemAttachment, or referenceAttachment."
      operationId: getAttachment
    delete:
      tags:
      - me.message
      summary: Delete attachment
      description: Delete an attachment from a user message.
      operationId: deleteAttachment
  /me/messages/{messageId}/attachments/createUploadSession:
    description: Provides operations to call the createUploadSession method.
    post:
      tags:
      - me.message
      summary: Create large file attachment upload session
      description: "Create an upload session that allows an app to iteratively upload\
        \ ranges of a file, so as to attach the file to the specified message. Use\
        \ this approach to attach a file if the file size is between 3 MB and 150\
        \ MB. To attach a file smaller than 3 MB, do a POST on the attachments navigation\
        \ property instead. As part of the response, this action returns an upload\
        \ URL that you can use in subsequent sequential PUT queries."
      operationId: createUploadSession
  /me/sendMail:
    description: Provides operations to call the sendMail method.
    post:
      tags:
      - me.user.Actions
      summary: Send mail
      description: "Send the message specified in the request body using either JSON\
        \ or MIME format. When using JSON format, you can include a file attachment\
        \ in the same sendMail action call. This method saves the message in the Sent\
        \ Items folder."
      operationId: sendMail
  /me/mailFolders:
    description: Provides operations to manage the mailFolders property of the microsoft.graph.user
      entity.
    get:
      tags:
      - me.mailFolder
      summary: List mailFolders
      description: "Get the mail folder collection directly under the root folder\
        \ of the signed-in user. The returned collection includes any mail search\
        \ folders directly under the root. By default, this operation does not return\
        \ hidden folders. Use the includeHiddenFolders query parameter to include\
        \ them in the response."
      operationId: listMailFolders
    post:
      tags:
      - me.mailFolder
      summary: Create mailFolder
      description: "Use this API to create a new mail folder in the root folder of\
        \ the user's mailbox. If you intend a new folder to be hidden, you must set\
        \ the isHidden property to true on creation. To create a mail search folder,\
        \ set the '@odata.type' property to '#microsoft.graph.mailSearchFolder' and\
        \ include the filterQuery and sourceFolderIds properties."
      operationId: createMailFolder
  /me/mailFolders/{mailFolderId}:
    description: Provides operations to manage the mailFolders property of the microsoft.graph.user
      entity.
    get:
      tags:
      - me.mailFolder
      summary: Get mailFolder
      description: "Retrieve the properties and relationships of a mail folder object.\
        \ You can specify a mail folder by its folder ID, or by its well-known folder\
        \ name, if one exists."
      operationId: getMailFolder
    delete:
      tags:
      - me.mailFolder
      summary: Delete mailFolder
      description: "Delete the specified mailFolder. The folder can be a mailSearchFolder.\
        \ You can specify a mail folder by its folder ID, or by its well-known folder\
        \ name, if one exists."
      operationId: deleteMailFolder
    patch:
      tags:
      - me.mailFolder
      summary: Update mailFolder
      description: Update the writable properties of a mailFolder object.
      operationId: updateMailFolder
  /me/mailFolders/{mailFolderId}/childFolders:
    description: Provides operations to manage the childFolders property of the microsoft.graph.mailFolder
      entity.
    get:
      tags:
      - me.mailFolder
      summary: List childFolders
      description: "Get the folder collection under the specified folder. You can\
        \ use the .../me/mailFolders shortcut to get the top-level folder collection\
        \ and navigate to another folder. By default, this operation does not return\
        \ hidden folders. Use the includeHiddenFolders query parameter to include\
        \ them."
      operationId: listChildFolders
    post:
      tags:
      - me.mailFolder
      summary: Create child folder
      description: "Use this API to create a new child mailFolder. If you intend a\
        \ new folder to be hidden, you must set the isHidden property to true on creation.\
        \ To create a mail search folder as a child, set the '@odata.type' property\
        \ to '#microsoft.graph.mailSearchFolder'."
      operationId: createChildFolder
  /me/mailFolders/{mailFolderId}/childFolders/{mailFolderId1}:
    description: Provides operations to manage the childFolders property of the microsoft.graph.mailFolder
      entity.
    get:
      tags:
      - me.mailFolder
      summary: Get child folder
      description: Retrieve the properties and relationships of a child mailFolder
        object.
      operationId: getChildFolder
    delete:
      tags:
      - me.mailFolder
      summary: Delete child folder
      operationId: deleteChildFolder
    patch:
      tags:
      - me.mailFolder
      summary: Update child folder
      operationId: updateChildFolder
components:
  securitySchemes:
    azureOAuth2:
      type: oauth2
      description: OAuth 2.0 authorization using Azure Active Directory (Microsoft
        Entra ID). Supports delegated permissions for accessing mail resources on
        behalf of the signed-in user.
      flows:
        clientCredentials:
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes:
            Mail.Read: Read access to all users' mail (application permission)
            Mail.ReadBasic: Read basic mail metadata (application permission)
            Mail.ReadWrite: Read and write access to all users' mail (application
              permission)
            Mail.Send: Send mail as any user (application permission)
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes:
            Mail.Read: Read access to user mail
            Mail.ReadBasic: Read basic user mail metadata
            Mail.ReadWrite: Read and write access to user mail
            Mail.Send: Send mail on behalf of the user
            MailboxSettings.Read: Read user mailbox settings
            MailboxSettings.ReadWrite: Read and write user mailbox settings
