name: CI

on:
  push:
    branches:
      - '**'
  repository_dispatch:
    types:
      check_connector_for_breaking_changes

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      pack ./outlookmail
            - name: Ballerina Test
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      test --test-report --code-coverage --coverage-format=xml ./outlookmail
              env:
                  REFRESH_URL: ${{ secrets.REFRESH_URL }}
                  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
                  CLIENT_ID: ${{ secrets.CLIENT_ID }}
                  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
                    
