name: CI

on:
  push:
    branches:
      - '**'
  repository_dispatch:
    types:
      check_connector_for_breaking_changes

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@2201.4.1
              with:
                  args:
                      pack ./outlookmail
            - name: Ballerina Test
              uses: ballerina-platform/ballerina-action/@2201.4.1
              with:
                  args:
                      test --code-coverage ./outlookmail
              env:
                  REFRESH_URL: ${{ secrets.REFRESH_URL }}
                  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
                  CLIENT_ID: ${{ secrets.CLIENT_ID }}
                  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

            # Read the ballerina test results
            - name: Read Ballerina Test Results
              id: test_results
              run: |
                content=`cat ./outlookmail/target/report/test_results.json`                
                content="${content//'%'/'%25'}"
                content="${content//$'\n'/'%0A'}"
                content="${content//$'\r'/'%0D'}"
                echo "::set-output name=testResultsJson::$content"

            # Print the code coverage information
            - name: Code Coverage
              run: |
                echo "Covered Code Lines : ${{fromJson(steps.test_results.outputs.testResultsJson).coveredLines}}"
                echo "Total Code Lines : $(expr ${{fromJson(steps.test_results.outputs.testResultsJson).missedLines}} + ${{fromJson(steps.test_results.outputs.testResultsJson).coveredLines}})"
                echo "Code Coverage Percentage : ${{fromJson(steps.test_results.outputs.testResultsJson).coveragePercentage}}"
                    
